### PR TITLE
feat: add execution context support

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds experimental execution context support.

It adds two functions:
- `with_context`: first argument is the context for the scope of the function, second argument is an expression reference
- `use_context`: takes one expression reference to be evaluated against the context

```
Data: { "a": 64.0 }
Context: { "a": 42.0 }

Program: use_context(&a) -> 42.0
Program: with_context({ a: 'abc' }, &use_context(&a)) -> 'abc'
Program: with_context({ a: 'abc' }, &[ a, use_context(&a) ]) -> [ 64.0, 'abc' ]
```

cc @springcomp

### CODE REVIEW

**Comment by eddycharly** [comment]
> Is this something you would like to propose as an alternative to the let expression being discussed with James ?

This is a simple experiment I wanted to play with. Of course I will follow the proposal.
That being said, what we have here is close to the new proposal, the execution context and bindings in the new proposal are very similar. The only difference is that the execution context can be anything and creating an execution context does not inherit from the parent (all contexts are isolated).

> I’m not sure why you need an expression-type to recall the reference to a in the use_context function?

Because the expression passed to `use_context` will be executed with the execution context as the current data context to be processed (if it was not an expression it would be evaluated before the call to `use_context` with the current data context).

**Comment by eddycharly** [comment]
The main idea here is to support an additional execution context aside the data context.

- `with_context` allows creating scopes where the execution context will be specific to the function scope (the new execution context can be created from the current data/execution contexts)
- `use_context` simply executes an expression with the execution context in place of the data context (it offers a way to consume what is in the execution context)

**Comment by springcomp** [comment]
I’m still not sold on using keywords, so that is why I like functions.

I think a `with_context()` or even `context()` function for short is perfect.

However, I would rather use a shorthand syntax for referencing identifiers from the context instead of a function.
What about re-using the `$` token. So that:

- `` $ `` is a reference to the input document.
- `` $a `` is a reference to identifier `a` from the context.

WDYT?

**Comment by springcomp** [comment]
> The main thing I don't like is that the context has to be a map. It makes sense if we consider it a binding and we introduce grammar changes but as long as we are only talking about execution context and function based implementation I don't see why we would need this at all.

Well there are three "topics" that must be resolved, one of which, in my opinion, we all agree on:

1. Whether the reference to a lookup / scoped / context variable be explicit or implicit. I think we all agree it should be explicit, contrary to what is being done currently with JEP-11.
1. Whether we use functions vs keywords vs other syntax to express / surface this feature.
1. Whether the scope / context should be isolated or support chained lookup.

The main advantage to the context being a map is that each property has a known name that can be referenced later on in downstream expressions. If you allow anything as the context, like a string or even an array, you would need to come up with a way to reference the context itself.

This would require introducing yet another token / syntax change into the grammar. I’m not opposed to this, but it needs to be discussed.
 
> In my mind chained contexts/scopes is not really present anymore in the reworked proposal. We are now talking about bindings that are essentially variables (or aliases). Using bindings makes the syntax more friendly at the cost of a more complex grammar. It also hides the details a bit more from custom functions perspective.

Well, whatever the syntax we end up with, either keywords, functions or even `let-expression` proposed below, you can always nest those calls in a complex expressions.

- James’s proposal: `` let <context> in ( let <nested-context> in <nested-expression> ) . <expression> ``
- Original JEP-11: `` let( { context: <context> }, & ( let( { nested_context: <nested-context> }, &<nested-expression> ) ) ) ``
- This prototype: `` with_context( { context: <context> }, & ( with_context( { nested_context: <nested-context> }, & <nested-expression> ) ) ) ``
- Alternative below: `` { context: <context> } => { nested_context: <nested_context> } => <nested-expression> ``

Basically, the syntax is irrelevant. There will always be a way to design nested expression and there you run into the problem of looking up an identifier in the "context". So which behaviour should apply ? Should we lookup the chain of contexts ? Should we stop at the first (innermost) level ? James and I (rather strongly) think there MUST be some chaining involve for this feature to be useful.

> This looks like a nice improvement to the supported syntax but is this directly related ? How does a lambda solves the problem of the execution context ?

You are right, this is just "syntax". A way to surface the feature. 
As an alternative to James’ `let <context> in <expression>` construct.
This is linked to topic number 2 in my list referred to above.

To be complete, here my full proposal:

```abnf
expression /= let-expression / reference
let-expression = multi-select-hash "=>" expression
reference = "$" identifier
```

**Comment by eddycharly** [comment]
> Whether the reference to a lookup / scoped / context variable be explicit or implicit. I think we all agree it should be explicit, contrary to what is being done currently with JEP-11.

No doubt, we all agree on this.

> Whether we use functions vs keywords vs other syntax to express / surface this feature.

Any solution that clearly identifies scopes would work. Using functions is natural in this context because functions map nicely with the concept of scope but using keywords work too (the `let <context> in (...)` is very clear about the scope definition).

> Whether the scope / context should be isolated or support chained lookup.

That's what i don't really follow, to me it looks like there's no chaining involved anymore. Eventually we can make the context available to inner contexts but in every scope we provide a set of bindings, chaining or not is an implementation detail.


> The main advantage to the context being a map is that each property has a known name that can be referenced later on in downstream expressions. If you allow anything as the context, like a string or even an array, you would need to come up with a way to reference the context itself.

It's true with bindings because because bindings are named by design.
If you consider the context can be anything and provide a way to act against this context it's just standard jmespath as we know it now applied to another object.

> This would require introducing yet another token / syntax change into the grammar. I’m not opposed to this, but it needs to be discussed.

I would recommend agains making things more complicated, bindings should be enough if we go this way.

**Comment by springcomp** [comment]
> If you consider the context can be anything and provide a way to act against this context it's just standard jmespath as we know it now applied to another object.

Oh I think I just realized your prototyped `with_context()` function actually swaps the original input document with another entirely. 😳

That's interesting.

How do you see the `$` `root-node` being used ? Is it referring to the original input document ? Or is it referring to the root of whatever "context" is current to the evaluating expression. In each of those cases, it seems a piece of the puzzle is missing.

However, I will need to think about your prototyped in a new light as I did not initially understood all its implications.

**Comment by eddycharly** [comment]
> Oh I think I just realized your prototyped with_context() function actually swaps the original input document with another entirely. 😳

Arff, sorry for failing to explain things clearly :(

What this PR contains is the introduction of a new context (called the execution context) completely separated from the actual context, and a mecanism to manipulate the execution context (`with_context` can transform the execution context and the result will be a new execution context for the scope of the function) / reference the execution context explicitly by calling `use_context` (will make the execution context the actual data context and the expression will be evaluated against it instead of the data context).

> How do you see the $ root-node being used ? Is it referring to the original input document ?

To me it looks like `$` (root node) is always about the original input document.

**Comment by eddycharly** [comment]
```
// data context: { "a": 64.0 }
// exec context: { "a": 42.0 }
with_context(
  // data context does not change when entering `with_context`, only the execution context will
  // data context: { "a": 64.0 }
  // exec context: { "a": 'abc' }
  { a: 'abc' },
  &use_context(
    // `use_context` makes exec context the actual data context and resets exec context to null
    // data context: { "a": 'abc' }
    // exec context: null
    &a // here `a` -> 'abc', an expression is always evaluated against the data context
  )
)

**Comment by eddycharly** [comment]
> how would you refer to the root of the curent context within a nested expression?

well, with `@` ;-)

```
// data context: original data
// exec context: null
with_context(
  // data context: original data
  // exec context: "WA"
  first_choice,
  &states[?name==use_context(
    // data context: "WA"
    // exec context: null
    &@
  )].cities[]
)
```

**Comment by eddycharly** [comment]
Hmm, not sure i answered your question.

> However, if indeed $ refers to the root of the original input document, we would need to write $.context.first_choice instead, which is fine.

I think we we would need to write `$.context.first_choice` as `$` does not change during the whole expression evaluation (I don't think other proposals had an influence on `$` (root node) behaviour did they ?)

**Comment by springcomp** [comment]
@eddycharly in one of your early examples, what is the following expression evaluating to?

`` with_context({ foo: 'bar' }, &use_context(&@)) ``

Given: `` { "baz": "qux" } ``, does it return `` { "foo": "bar" } `` or the original input document?

**Comment by eddycharly** [comment]
It returns `{ "foo": "bar" }`

**Comment by springcomp** [comment]
> It returns `{ "foo": "bar" }`
> 
> The above expression is similar to:
> 
> ```
> Input: { "foo": "bar" }
> Expression: @
> ```

Yes, sorry, I think [you have answered that](https://github.com/jmespath-community/go-jmespath/pull/58#issuecomment-1476181651) previously.

**Comment by springcomp** [comment]
Can you clarify what you call `data context` and `execution context`?

I’m preparing [a summary](https://gist.github.com/springcomp/38488b272fe8ec85bbd1d98c605f0ca5) and would like all to agree on proper terms?

**Comment by eddycharly** [comment]
Data context is the document being processed (what we have today in jp), this is the data object being processed.

Execution context is another context passed through the interpreter, it is not used directly but can be manipulated using `with_context` to change the execution context for the scope of the function or `use_context` to execute an expression against the current context.

The main point is that a single object is usually not enough, it seems reasonable to have the same expression, the same object to process and some external data (the execution context).

**Comment by springcomp** [comment]
> Data context is the document being processed (what we have today in jp), this is the data object being processed.
>  
> Execution context is another context passed through the interpreter, [introduced by] `with_context` 
 
For the sake of the discussion referred to above, would you agree on the following terms?

The original JMESPath specification did not need to name concepts as there was only a single execution "thing" to work on. JEP-11 that we initially adopted in JMESPath Community explicitly names this thing the `execution context`. After the first evaluation, the `execution context` **is** the original input JSON document which is mutated as evaluation progresses.

With [JEP-19](https://github.com/jmespath-community/jmespath.spec/blob/main/jep-017-root-reference.md), JMESPath Community supports the `$` `root-node` reference, making the original input JSON document available at all times. This effectively makes JMESPath expressions able to operate on both a current `execution context` and an original input JSON document at any one time – both of which start as one and the same before evaluation.

JEP-11 further introduces the concept of `scope` (let’s ignore that multiple `scope` objects exist and are organized as a stack). This means that JMESPath expression can now then operate on three "things" at any one time, the current `execution context`, the original input JSON document **and** the current `scope`.

If we agree on those terms – which may later change, do I have the correct understanding that you are using the following terms?

- Your _data context_ is the original input JSON document **and** what I refer to as the current `execution context` at any one time ?
- Your _execution context_ is what I rather name `scope` ? Is that what you name _bindings_ sometimes as well?

**Comment by eddycharly** [comment]
Closing, let's focus on new `let` support.

**Pull request closed without merging**
