### PR TITLE
refactor: introduce Scope interface and make scopes immutable

### PR DESCRIPTION
**Pull request by eddycharly**
This PR introduces a `Scope` interface and makes scopes immutable.

With this PR scopes are chained together creating a new scope every time we add an element in the chain, this way we don't need to push/pop elements.

### CODE REVIEW

**Comment by springcomp** [comment]
@eddycharly that is definitely a bug.
The following evaluation should hold:

`` search( let({root: @}, &root).root, {}) -> null ``

However, it currently returns the value of `root` since `popScope()` was never called. ☹.

I do not know how to make `Scopes` immutable. The behaviour is mostly correct: each new invocation of the `let()` function must open up a new scope in the stack _only for the duration of evaluating the `let()` function_. So nested calls do indeed push to the stack, whereas the closing parens should pop from the stack.

The tricky thing here is to still support concurrent evaluations of, say, the same AST with two different inputs concurrently. In that case, each evaluation must have its own scope.

**Comment by eddycharly** [comment]
@springcomp i added a unit test to cover the test case you provided in #30

**Comment by springcomp** [comment]
@eddycharly thanks for highlighting the issue.

You will find [an updated compliance test suite](https://github.com/jmespath-community/jmespath.test/commit/8a1b382c64d1873e9c90612fb73120277f5a1c5e) to test this specific case.

Thanks to your changes, I was also able to fix the Python implementation.

**Comment by eddycharly** [comment]
I suspect we have more issues here but this one was obvious.
I'll dig deeper soon to check if what I have in mind is true.

**Pull request merged**
