### PR TITLE
refactor: simplify passing interpreter to functions

### PR DESCRIPTION
**Pull request by eddycharly**
This PR simplifies the way we pass the interpreter to functions.

### CODE REVIEW

**Review by springcomp — COMMENTED** [review]
I must admit I do not fully comprehend this code.

In my mind, not all functions need access to the interpreter.
What would be a rationale (pros / cons) that warrants this change?

**Comment by eddycharly** [comment]
> not all functions need access to the interpreter.

true but you don't know if a function needs it or not, it's up to the function to decide.
abusing arguments is not a good solution, passing the interpreter and letting the function use it if necessary is a more robust design IMHO.

**Comment by eddycharly** [comment]
> This prevents leaking the raw interpreter to function codes

If it is an issue we can pass a `func` instead.
Let me check the python implementation.

**Comment by eddycharly** [comment]
I don't know much about Python unfortunately but does an `Expression` knows about the `Interpreter` ?

**Comment by eddycharly** [comment]
@springcomp I moved to passing a `func` instead of the `Interpreter` interface, looks better to you ?

**Comment by springcomp** [comment]
> […] does an `Expression` knows about the `Interpreter` ?

Yes, in essence, an Expression is an abstraction over the Interpreter.

**Comment by springcomp** [comment]
> @springcomp I moved to passing a `func` instead of the `Interpreter` interface, looks better to you ?

I think my concern is that functions should not in my mind have access to more than their specified arguments.
I think a using func is a good abstraction, but I still favor if only `*By()` functions do have this "extra" argument.
Ideally, they should receive a proper ExpressionType argument.

**Comment by eddycharly** [comment]
I think I see what you mean, is this ok if we merge what we have here and I keep thinking about it ?

**Pull request merged**
