### PR TITLE
chore: add golangci-lint job

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds a `golangci-lint` job.

cc @springcomp looks like gh actions are not running, are they disabled when PRs come from forks ?

### CODE REVIEW

**Comment by springcomp** [comment]
> cc @springcomp looks like gh actions are not running, are they disabled when PRs come from forks ?

I have no idea 😶

**Comment by eddycharly** [comment]
Let me know if you want some help, I can guide you on configuring the repo if you need help on that.

Looks like we are on the same time zone, we can catch up on slack if it's ok.

**Comment by springcomp** [comment]
> Let me know if you want some help, I can guide you on configuring the repo if you need help on that.

Thanks a lot for your offer and your dedication.
FYI I had asked recently @JimBugwadia to become the official maintainer of this repository and he kindly accepted.

I think this is awesome to have such feedback.
I will be stepping down maintaining this repository.

**Comment by eddycharly** [comment]
@springcomp can you add me as a maintainer of this repo ?

**Comment by springcomp** [comment]
> @springcomp can you add me as a maintainer of this repo ?

✔

**Comment by eddycharly** [comment]
@springcomp it looks like i don't have the necessary permissions to configure gh actions, branch protection, etc...

**Comment by springcomp** [comment]
> @springcomp it looks like i don't have the necessary permissions to configure gh actions, branch protection, etc...

I’m OK to give one or both of you `admin` rights.
Can you both give me confirmation as what is the best course of action going forward ?

**Comment by eddycharly** [comment]
Sure, please go ahead.

**Comment by JimBugwadia** [comment]
@springcomp - yes, please proceed.

**Pull request merged**
