### PR TITLE
feat: add custom functions support

### PR DESCRIPTION
**Pull request by eddycharly**
WIP to add custom functions support from kyverno jmespath fork.

### CODE REVIEW

**Review by springcomp — CHANGES_REQUESTED** [review]
@eddycharly Thanks tons for your contribution.

I see there are a mix of case-fixing (upper/lower case) and actual changes to support registration of custom functions.

Can this be split into two PRs ?

**Comment by eddycharly** [comment]
> I see there are a mix of case-fixing (upper/lower case) and actual changes to support registration of custom functions.

If we want to support custom functions we need to make a couple of symbols public and available from the outside.

**Comment by springcomp** [comment]
> If we want to support custom functions we need to make a couple of symbols public and available from the outside.

Ah, indeed, that got me by surprise here.
Still, even in the same PR can this be split into two / multiple commits: one for enabling visibility, and another one to actually add some features?

**Comment by eddycharly** [comment]
Ok, aren't we going to squash commits at the end anyway ?

Well, this is still WIP, I can split this into multiple PRs when it's ready if you prefer.

**Comment by springcomp** [comment]
> Ok, aren't we going to squash commits at the end anyway ?

Sure thing. Still for the code review, it’s easier to reason about if I can compare scoped commits.
I’m being a bit nitpicky here, but in the end, you’re right, it does not make a whole lot of difference as long as compliance tests succeed.

**Comment by eddycharly** [comment]
@springcomp yes, we discussed it internally and we both agreed on this. In the end I see some interesting improvements in this repo compared to the official one so the plan will probably be to switch to this implementation in kyverno at some point.

**Comment by eddycharly** [comment]
BTW, thanks for offering us this opportunity ;)

**Comment by springcomp** [comment]
@eddycharly I see that Kyverno uses a whole host of custom functions over the original upstream repository.

Can I ask you to consider **not** adding those functions to this repository.
But _instead_, consider hosting those custom functions in their own library / package so that they can be registered from your client code?

Would that be something you would be comfortable with?

**Comment by eddycharly** [comment]
@springcomp definitely, i don't want to add any function in this repo, this is the whole purpose of supporting user defined functions.

Custom functions will stay in our repo and we will register them in the jp interpreter at startup.

**Comment by eddycharly** [comment]
I see that adding support for lexical scopes changed the way the interpreter is created though.
Function registration must be done differently than in our fork but it's no big deal. I'm thinking how this could be improved with something like an interpreter context... 

Anyway, plenty of things to improve first. Shall I add you as a reviewer ?
For example I'd like to split the code into multiple packages, WDYT ?

**Comment by springcomp** [comment]
> […], plenty of things to improve first. Shall I add you as a reviewer ? 
> For example I'd like to split the code into multiple packages, WDYT ?

Sure go ahead with any structural changes you see fit.

The only assumptions I have for repositories under the JMESPath Community organization are:
- Make reasonable effort to keep up with changes to the spec.
- Link to the compliance test suite as the single source of truth.
  - I have chosen to link by way of Git submodules but any solution would do. For instance, one might want to dynamically fetch the latest changes during CI build.

Maybe I will need to come up with a _maintainer’s covenant_ or such. 🤔
 
I‘m definitely interested in learning more about Go and following structural changes made to this library, so, indeed, please keep me in the loop. I literally [learned go in 12 minutes](https://youtu.be/C8LgvuEBraI) last week end and set out to implement the changes during my vacations last week while others were performing mountainous outdoor activities 😁. But you know what they say: "_fake it until you make it_" !

**Comment by eddycharly** [comment]
Closing in favour of #42

**Pull request closed without merging**
