### PR TITLE
refactor: introduce Interpreter interface

### PR DESCRIPTION
**Pull request by eddycharly**
This PR introduces the `Interpreter` interface.

### CODE REVIEW

**Review by springcomp — APPROVED** [review]
I’m learning so much.

Such simple and obvious changes, yet they did not occur to me 😶.

**Comment by eddycharly** [comment]
@springcomp I wonder why we never call `popScope` in the code...

**Comment by eddycharly** [comment]
> Such simple and obvious changes

We don't want to expose the whole `treeInterpreter` to users when they are going to register custom functions, yet they need an interface to be able to call `Execute`.

**Comment by springcomp** [comment]
> @springcomp I wonder why we never call `popScope` in the code...

You are right. I think that _may be_ a bug.

The best place to do this is after evaluation of the `let()` function.
In fact, here is the code I use in the [JMESPath .NET implementation](https://github.com/jdevillard/JmesPath.Net/blob/eef90705926887917d92b262251990965b44a96a/src/jmespath.net/Functions/LetFunction.cs#L23-L35).

I actually do not know how to do that in this implementation.
Nor did I know how do do that either in the Python port.

I think I maybe able to manifest the bug using two consecutive `let()` functions – by opposition with _nested_ – calls.

**Comment by eddycharly** [comment]
I opened https://github.com/jmespath-community/go-jmespath/pull/31#issuecomment-1449988699

Looks like treating scopes as immutable data structures is the correct approach. WDYT ?

**Comment by eddycharly** [comment]
@springcomp #31 makes the scope immutable.

**Pull request merged**
