### PR TITLE
Parsing upcoming `let-expression`

### LINKED ISSUE #53: fix scope related bug
This test should fail:
```
	{
		args: args{
			expression: `let({"b": @.a}, &a.b)`,
			data: map[string]interface{}{
				"a": 42.0,
			},
		},
		want: 42.0,
	}
```

Once `&a` has been looked up from the scope, we should not use the scope again to lookup `.b`.

@springcomp am I right thinking we have a bug here ?

### PR DESCRIPTION
**Pull request by springcomp**
This PR implements the parsing of `let-expression` rules as they are anticipated to land in an [upcoming proposal](https://github.com/jmespath/jmespath.jep/pull/18).

This PR does not implement the lexer, nor does it include any expression evaluation logic.
This is a work in progress.

Fixes #53

### CODE REVIEW

**Comment by springcomp** [comment]
**Known Limitations** (aka Bugs ☹)

- I’m currently parsing the sequence `$foo =` as part of the `bindings`. However, it may also appear as a legitimate `comparison-expression`

**Comment by springcomp** [comment]
My setup seems broken, I do not understand how to lint my code ☹

**Comment by eddycharly** [comment]
@springcomp does it work when you try to parse `let $root = @ in $root.a` ?

I have `Unexpected token at the end of the expression: TOKRoot`.

**Comment by eddycharly** [comment]
In `let $root` it looks like `$` is tokenized as `TOKRoot`.

**Comment by springcomp** [comment]
I must have forgotten to push this change 🙄.

The reason is that we use `$` for `root-node` as well. I have actually made the same fix in the [Python](https://github.com/jmespath-community/python-jmespath/commit/53bf4397ef54265674563605c44f27c9197db15a) port.

Basically, `$` is no longer an ambiguous single char token but must be handled with a dedicated case.

If you can follow the Python diff you will see what I mean. If you need, howevee, I can have a look at it tomorrow.

**Comment by eddycharly** [comment]
> Basically, $ is no longer an ambiguous single char token but must be handled with a dedicated case.

Yeah i was tracking it down, it see it in:
```
var basicTokens = map[rune]TokType{
	'.':      TOKDot,
	'*':      TOKStar,
	',':      TOKComma,
	':':      TOKColon,
	'{':      TOKLbrace,
	'}':      TOKRbrace,
	']':      TOKRbracket, // tLbracket not included because it could be "[]"
	'(':      TOKLparen,
	')':      TOKRparen,
	'@':      TOKCurrent,
	'$':      TOKRoot,
	'+':      TOKPlus,
	'%':      TOKModulo,
	'\u2212': TOKMinus,
	'\u00d7': TOKMultiply,
	'\u00f7': TOKDivide,
}
```

I will give a look at the python implementation, i think i can read some basic python 🤞

**Comment by eddycharly** [comment]
Ok, parsing is passing now, I'll start implementing the bindings tomorrow.

**Comment by springcomp** [comment]
> Ok, parsing is passing now, I'll start implementing the bindings tomorrow.

Perfect. Please note that I did not include the lexing either 😏

**Comment by eddycharly** [comment]
> Please note that I did not include the lexing either

I feel like parsing is not robust enough, see #68 for example (`|` is not necessarily a `ASTPipe`, depending on the context it can be an `ASTField` too).

**Comment by eddycharly** [comment]
> I did not include the lexing either 

I did this:

```golang
func (lexer *Lexer) consumeVarRef() token {
	// Consume runes until we reach the end of an unquoted
	// identifier.
	start := lexer.currentPos - lexer.lastWidth
	for {
		r := lexer.next()
		if r < 0 || r > 128 || identifierTrailingBits[uint64(r)/64]&(1<<(uint64(r)%64)) == 0 {
			lexer.back()
			break
		}
	}
	value := lexer.expression[start:lexer.currentPos]
	return token{
		tokenType: TOKVarref,
		value:     value,
		position:  start,
		length:    lexer.currentPos - start,
	}
}
```

**Comment by springcomp** [comment]
> I did this:

This seems perfect. 👍 As the check for a character that starts an `unquoted-identifier` is handled when testing `root-node` vs `varref`.

**Comment by eddycharly** [comment]
@springcomp I implemented the interpreter part, WDYT ?

**Comment by springcomp** [comment]
That’s nice. I think we are almost there.

Currently, there are three[compliance tests] failing.

- `` let $a = 'top-a' in let $a = 'in-a', $b = $a in $b `` (bindings only visible within expression clause)

I have the feeling that scopes are not correctly pushed / popped appropriately.

- `` $noexist `` (currently returns `null` whereas it should fail with `undefined-variable` )
- `` [let $scope = 'foo' in [$scope], $scope] `` (referencing out of scope variables)

**Comment by springcomp** [comment]
> I didn't implement undefined-variable error (there's a TODO in this PR).

Sorry I missed that.

**Comment by eddycharly** [comment]
> variable

I'll do that asap, should not be long.

**Comment by eddycharly** [comment]
@springcomp can you point me to the python implementation please ?

**Comment by springcomp** [comment]
> @springcomp can you point me to the python implementation please ?

https://github.com/jmespath-community/python-jmespath/tree/feature/let-expression

**Comment by springcomp** [comment]
That works great !

Implementation looks good to me.
I like how go enables to discard a scope using the `defer` keyword.

👍

**Comment by eddycharly** [comment]
> I like how go enables to discard a scope using the defer keyword.

It's similar to `finally` in .NET

**Comment by eddycharly** [comment]
I'm curious why we don't allow referencing previous bindings though https://github.com/jmespath/jmespath.py/pull/307#discussion_r1149227788

**Comment by springcomp** [comment]
> I'm curious why we don't allow referencing previous bindings though

My understanding is that:

`` let $a = 'top-a' in let $a = 'in-a', $b = $a in $b ``

My understanding is that as your are creating the second nested level of bindings, you are defining a shadow value for `a` but this value is not yet available - _visible_ as the proposal posits - to the other expressions used to the create the binding.

This seems logical to me. As you would not want to have side effects based upon the order in which each implementation would want to create the binding.

Let's say an implementation would create the binding in alphabetical order of variable names. Or in reverse order. Or in an unspecified order. They would result in different output from one another.

**Comment by eddycharly** [comment]
> For this to work though, the spec would need to absolutely specify the order in which binding variables are created.

I was assuming variables were initialised in the declaration order.

**Comment by springcomp** [comment]
> @springcomp shall we get this in ?

Good question. I actually have no idea how much time James will allow for the proposal to reach consensus.
In any case, this is a better proposition than the `let()` function, so I would include this anyway.

I will proceed with other implementations as well and start the deprecation process in the spec.

**Comment by eddycharly** [comment]
@springcomp i added unit tests for the bindings package.

**Comment by springcomp** [comment]
@eddycharly can we include in this pull request provisions for settings a [global scope](https://github.com/jmespath/jmespath.jep/blob/7dc32538aa75733ca181247c6a2580f3ca53844c/proposals/0000-lexical-scope.md#unbound-values-error-at-evaluation-time-not-at-compile-time) from the `jp` command-line.
I’m referring to this part of the spec:

> The JEP also requires that unbound values error at evaluation time, not at compile time. This enables implementations to bind an initial (global) scope when a query is evaluated. This is something that other query languages provide, and is useful to define fixed queries that only vary by the value of specific variables.

**Comment by eddycharly** [comment]
> @eddycharly can we include in this pull request provisions for settings a [global scope](https://github.com/jmespath/jmespath.jep/blob/7dc32538aa75733ca181247c6a2580f3ca53844c/proposals/0000-lexical-scope.md#unbound-values-error-at-evaluation-time-not-at-compile-time) from the jp command-line.

I'll do that tomorrow 👍

**Comment by springcomp** [comment]
@eddycharly FYI `let-expression` is now [part of the language](https://jmespath.site/main/#spec-let-expressions) having recently been approved by James.

**Comment by eddycharly** [comment]
@springcomp yeah i saw that, awesome !

**Comment by springcomp** [comment]
Hello @eddycharly @JimBugwadia should this pull request be merged ?

**Comment by eddycharly** [comment]
@springcomp sorry, we were quite busy during the last weeks.

I think this is good to merge, we can improve in follow-up PRs if it's ok.

**Comment by springcomp** [comment]
> I think this is good to merge, we can improve in follow-up PRs if it's ok.

That’s perfect for me.
Please, merge at your own pace.

Thanks a lot.

**Pull request merged**
